name: Deploy Lab01 to Cloud Run

# trigger on pushes to main branch
on:
  push:
    branches:
    - "main"

env: 
  GCP_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT }}
  GCP_REGION: europe-north1

# define jobs to execute
jobs:
  deploy:
    # ubuntu vm has docker pre-installed
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      # use pre-defined action to checkout code
      uses: actions/checkout@v4

    - name: Auth GCP
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: Install gcloud cli
      # use pre-defined action to install gloud cli
      uses: google-github-actions/setup-gcloud@v1
      #  Configure gcloud cli with secrets
      # with:
      #   project_id: ${{ secrets.GOOGLE_PROJECT }}
      #   service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      #   export_default_credentials: true

    - name: Build and push Docker image
      run: |  # pipe lets you define multi-line commands
        # Authenticate against Google Cloud
        gcloud auth configure-docker europe-north1-docker.pkg.dev
        # Build Docker image
        docker build -t europe-north1-docker.pkg.dev/$GCP_PROJECT_ID/gcp-lab01/lab01:latest .
        # Push Docker image to Google Artifact repository
        docker push europe-north1-docker.pkg.dev/$GCP_PROJECT_ID/gcp-lab01/lab01:latest
        # Deploy to Cloud Run
        gcloud run deploy lab01 --image europe-north1-docker.pkg.dev/$GCP_PROJECT_ID/gcp-lab01/lab01:latest --platform managed --region $GCP_REGION

